version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - default
  app:
    restart: always
    build: .
    environment:
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    ports:
      - 5000:5000
    volumes:
      - .:/app
    networks:
      - default
    depends_on:
      - postgres
    entrypoint: ["python", "app.py"]